### ISSUE TITLE
paymentservice_purchase_request does not work.

### ISSUE THREAD

**Issue by giorgosgs** [blackberry/SDL#27]
if (paymentservice_purchase_request(digital_good_id, digital_good_sku, digital_good_name, metadata, purchase_app_name, purchase_app_icon, get_window_group_id(), &request_id) != BPS_SUCCESS)

Does not work because it needs "get_window_group_id()".
This needs "if (screen_create_window_group(screen_win, get_window_group_id())" to be set but we cannot do that since SDL uses its own window and not "screen_window_t". 

So we cannot add in-app purchases system in a blackberry SDL app.

thanks,

**Comment by jnicholl** [comment]
Hello,
As a workaround, take a look at PLAYBOOK_CreateWindow in SDL_playbookvideo.c. It sets the window group id (it's just a string) so you can set it in the same way to pass into the payment service. I'm not sure what the right way for an app to get this info from SDL is directly, so we'll still need to take a look at that.
Thanks for letting me know.

**Comment by giorgosgs** [comment]
There are many issues to be addressed:

1) I use libSDL12.so compiled library. How can I get the string of the window group id from there?
2) paymentservice needs "bps_get_event" to get "paymentservice_get_domain()" events. We already have "SDL_PollEvent". If we additionally implement "bps_get_event(&event, -1);" the game becomes very slow and unplayable.
How can we catch "paymentservice" events from SDL_PollEvent?
We cannot even catch a simple "dialog_get_domain()" event from a dialog 'yes' or 'no' button!

Thanks,

**Comment by jnicholl** [comment]
Again, these are mostly workarounds, and untested ones at that.
1) You can look at the SDL source code I referenced to find out the code that generates the string used for the window group and simply copy it. You can't get it from the library, but I'm not sure how that would be possible even with code changes in the library, unless we add a BlackBerry-specific addition to the api.

2) My understanding was that bps events can be registered for on multiple threads. Can you simply spawn a new thread to handle the desired bps events?

**Comment by giorgosgs** [comment]
This is the code that generates the string used for the window group:

``` javascript
        char groupName[256];

        rc = screen_create_window(&screenWindow, _priv->screenContext);
        if (rc) {
            SDL_SetError("Cannot create window: %s", strerror(errno));
            return NULL;
        }

        snprintf(groupName, 256, "sdl-%dx%dx%d-%u", width, height, bpp, time(NULL));
        rc = screen_create_window_group(screenWindow, groupName);
        if (rc) {
            SDL_SetError("Cannot set window group: %s", strerror(errno));
            screen_destroy_window(screenWindow);
            return NULL;
        }
```

I dont get it. How can I just copy it? The window group is already created, I cannot create another one. How can I find the first one?

Thanks,

**Comment by jnicholl** [comment]
Ah, I see the problem. At some point, the groupName was going to use getpid instead of time(NULL), which should mean it would be deterministic. You could change that and rebuild SDL, and use the same groupName as the window group id.
Alternatively, looking at SDL, it looks like the syswm header is supposed to be where such things are added. I won't get a chance to implement it for some time, but I think it should be fairly straightforward to do.

**Comment by jnicholl** [comment]
asimonov-rim made a change to SDL_syswm.h to provide the screen_context and screen_window. I believe you should be able to get the window group id from the screen_window.
Did the threaded approach work for other bps events?

**Comment by giorgosgs** [comment]
How to get the existing screen_window from this change? I try like that... What am i missing for the window?

``` javascript
    SDL_SysWMinfo info;
    SDL_VERSION(&info.version);
    SDL_GetWMInfo(&info);
```

thanks.

**Comment by jnicholl** [comment]
That looks right, I think info.window should return the screen_window_t and info.context should return the screen_context_t.
I'm not exactly sure, you may need to make sure SDL.h is included before SDL_syswm.h to ensure the right structure is defined in the latter file.

**Comment by giorgosgs** [comment]
When I use:

``` javascript
screen_window_t wins = info.window;
```

I get this error:
"error: 'struct SDL_SysWMinfo' has no member named 'window'"

Maybe because in "SDL_syswm.h" "#elif defined(SDL_VIDEO_DRIVER_PLAYBOOK)" is grayed out like its no active. Should it be active? Why SDL_VIDEO_DRIVER_PLAYBOOK is not recognized?

Thanks,

**Comment by jnicholl** [comment]
It should be defined. Perhaps you need to #include <SDL.h> before you include SDL_syswm.h? It should be defined in the SDL config.
Also, you want to make sure you have **PLAYBOOK** defined, I believe.

**Comment by giorgosgs** [comment]
I used with __PLAYBOOK_ and SDL_VIDEO_DRIVER_PLAYBOOK defined:

``` javascript
    SDL_SysWMinfo info;
    SDL_VERSION(&info.version); // this is important!
    SDL_GetWMInfo(&info);
    char str[64];
    screen_get_window_property_cv(info.window, SCREEN_PROPERTY_GROUP, sizeof(str), str);
```

and it worked!
I use the "paymentservice_set_connection_mode(true);" and a thread like you suggested to catch the events with "bps_get_event(&event, -1);" but now I have another weird error: Everytime I press a button at the payment window (Eg: to buy something or to cancel it) I get a "SDL_PollEvent" = SDL_QUIT and the game quits. 

Why is that? Do you have any idea? How can the "paymentservice" send a SDL event quit?

Thanks,

**Comment by asimonov-im** [comment]
That seems quite bizarre.
Could you try setting a breakpoint in SDL_PrivateQuit() in under src/events/SDL_quit.c? This is the function that posts the SDL_QUIT event and it would be helpful to know where it is getting called from.

**Comment by asimonov-im** [comment]
I just pushed a minor change to SDL that should hopefully fix the issues - cff3ad3f298be993290a13877e4b393503b5bdda

**Comment by giorgosgs** [comment]
Ok this fixed the issue, thanks!

Now we go forward to other issues. I cannot catch the "bps_event_get_domain(event) == paymentservice_get_domain()" events. I have created a thread like 'jnicholl' suggested like that:

``` javascript
    //create a thread for events
    pthread_attr_t attr;
    pthread_attr_init( &attr );
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);
    pthread_create(NULL, &attr, &thread_running, NULL);
```

then I try to catch the "paymentservice" events like that:

``` javascript
void* thread_running(void* arg)
{
SDL_bool done=SDL_FALSE;

    while (!done)
    {
            bps_event_t *event = NULL;
            bps_get_event(&event, -1);
            if (bps_event_get_domain(event) == paymentservice_get_domain()) {
                 printf("comes in here!\n");
            }
    }

    return(0);
}
```

But nothing happens. I even tried a simple dialog with "bps_event_get_domain(event) == dialog_get_domain()" but it never got there!

How should I do this? Can we catch these events from "SDL_PollEvent"?

Thanks,

**Comment by asimonov-im** [comment]
Try out the payment branch of SDL_GL (https://github.com/asimonov-rim/SDL_GL). Also take a look at the PaymentService NDK sample (https://github.com/blackberry/NDK-Samples).
