### ISSUE TITLE
Fullscreen Renders Improperly in Portrait (not closed)

### ISSUE THREAD

**Issue by giorgosgs** [blackberry/SDL#28]
I have the same issue reported as closed on my playbook. (I use the latest emulate SDL build. Downloaded and compiled today)

In my "bar-descriptor.xml"  I have:
    < initialWindow >
        < aspectRatio >landscape< / aspectRatio >
        < autoOrients >false< / autoOrients >
        < systemChrome >none< / systemChrome >
        < transparent >false < / transparent >
    < / initialWindow >

The game normally runs in landscape.
If I hold the device in landscape orientation, and begin an application, it runs just fine.

if I begin the application while I am holding the PlayBook in portrait, the screen initializes in a squished view.
Sometimes (rarely) it renders correctly. It seems to be a race condition as stated in the 'closed' similar issue.

(I use bbndk-2.0.1 and playbook 2.0.1.358)

**Comment by giorgosgs** [comment]
Any help?

I cannot fix this issue myself. It seems that when the app starts (holding the PlayBook in portrait) it is still in portrait and the program sees a resolution of 600x1024 and acts accordingly. But after a second the orientation changes to landscape (because I have set: < aspectRatio >landscape< / aspectRatio >) but its too late since the program started with 600x1024 and not 1024x600. 
What can we do?

**Comment by jnicholl** [comment]
I asked asimonov to reply, I thought this issue was fixed. It doesn't happen with frogatto, and that uses SDL. Are you using opengl with SDL?

**Comment by giorgosgs** [comment]
Opengl and SDL. I hope it was fixed too...

**Comment by jnicholl** [comment]
Do you open multiple windows, or only a single one? Frogatto is also OpenGL, so it can't just be OpenGL-related.

**Comment by jnicholl** [comment]
I haven't been able to reproduce the squished display, but I did find some problems related to opening an application in portrait mode. What resolution are you setting for your window (SDL_SetVideoMode)?

**Comment by asimonov-im** [comment]
Unfortunately, I am unable to reproduce the issue with my sample application (https://github.com/asimonov-rim/SDL_GL). Perhaps you could try building and running the sample on your device and see if the cube becomes squished.

Some other things to consider:
1. Make sure you have the commit that appears to fix the issue for us - 2848c718671f8859c5b240464c84202ccd86b876
2. If possible, send us your code or a stripped-down version of it that still has the issue.

**Comment by giorgosgs** [comment]
I use a single window.

I tried the SDL_GL sample and when I start it with landscape mode it works fine. When I start it with portrait mode then it crashes before it even begins. I tried to debug it but it worked fine (seems a race condition bug since in debug it started slower and had time to switch to landscape)

I have the fixes (commit) in my SDL code.

``` javascript
//Auto adjust resolution
const SDL_VideoInfo* myMonitor = SDL_GetVideoInfo();
//SET
SCREEN_WIDTH = myMonitor->current_w;
SCREEN_HEIGHT = myMonitor->current_h;

gv.window = SDL_SetVideoMode(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_BPP, SDL_OPENGL | SDL_FULLSCREEN);
    if (!gv.window) {
        fprintf(stderr, "Couldn't set %dx%d video mode: %s\n", SCREEN_WIDTH, SCREEN_HEIGHT, SDL_GetError());
        //return false;
    }
```

**Comment by asimonov-im** [comment]
jnicholl and I committed two patches, the most recent of which is meant to force SDL_GetVideoInfo to return landscape dimensions. We don't know why SDL_GL would crash in portrait mode (is there a log message?).
Hopefully they'll help, it's hard to tell what's going on when we don't seem to get any of the same results.

**Comment by giorgosgs** [comment]
I think I know why SDL_GL crashes. 
I did almost the same patch myself before 2 days (switched the height and width if the height is bigger than the width) and it crashed because "SDL_SetVideoMode" could not set that resolution.
I suppose at that exact time the orientation is still in portrait and we ask the "SDL_SetVideoMode" to create a resolution that it cannot create. After some time (milliseconds) the program changes to landscape automatically but its too late.

I guess SDL_GL tries to "SDL_SetVideoMode" of 1024x600 when the app is still in 600x1024 and SDL_SetVideoMode crashes.

**Comment by jnicholl** [comment]
My understanding was that SDL_SetVideoMode should only reject resolutions based on what is in the list of possible display modes, and with the recent change, it should enforce landscape modes as the only possible display modes?
Would it be possible to copy the exact error message from when the program exits, after updating to the newest version?
Thanks!

**Comment by giorgosgs** [comment]
ok will do

**Comment by giorgosgs** [comment]
I confirm that the bug is now fixed!
