### ISSUE TITLE
Click of program hangs...

### ISSUE THREAD

**Issue by giorgosgs** [blackberry/SDL#29]
I use SDL and OpenGL ES. Playbook 2.0.1.358

I have a strange bug. Most of the times the game runs fine.
Sometimes (seems randomly and commonly) seems that the game hangs. Its unresponsive.

1) I have added the debugger and no error ocurrs. All runs fine. Then game is live (moves, sound etc) but the touch screen is dead. I have to close it and restart it to work. Is it a "TouchControlOverlay" issue? Should I write it there?

The only warnings I get when the game starts in debug mode is:

``` javascript
MsgNak received - resending
Remote target is little-endian
[New pid 145965214 tid 2]
warning: Could not load shared library symbols for libusc.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for libsrv_um.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for libpvr2d.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for libIMGegl.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for wsegl-screen.so.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for libImgGLESv1_CM.so.
Do you need "set solib-search-path" or "set sysroot"?
[New pid 145965214 tid 3]
```

thanks

**Comment by jnicholl** [comment]
The warnings listed aren't really indicating an error, they're normal. For being unresponsive, that seems strange. Are you actually using TouchControlOverlay? If you are, what does your sdl-controls.xml file look like? If you don't have one, you're not actually using TouchControlOverlay.

## Can you set a breakpoint in PLAYBOOK_PumpEvents and see if events are being received?

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by giorgosgs** [comment]
You are right. No, I dont have one. I made a simple one:

``` javascript
<?xml version="1.0" encoding="ISO-8859-1"?>
<emulation version="1">
<touchscreen x="0" y="0" width="1024" height="600"/>
</emulation>
```

...and placed it in the project directory. Where the other xml file is: bar-descriptor.xml
How do I use it now? Do I just catch it in SDL_PollEvent with SDL_MOUSEMOTION, SDL_MOUSEBUTTONUP,  SDL_MOUSEBUTTONDOWN?

**Comment by jnicholl** [comment]
If you just want to get typical touch events, I think you don't need one. TouchControlOverlay is really meant to translate touch events in particular areas into keyboard or mouse input, usually when porting games from desktop.
There are some examples in the TouchControlOverlay wiki.

Without TouchControlOverlay, you should be able to get good touch events as SDL mouse events, I believe there should be a different 'mouse id' per touch point.

**Comment by giorgosgs** [comment]
If I dont need one then we go back to my initial error:
Do you have an idea why (randomly) my game touch input hangs?
(The rest of the game plays fine but the input touch hangs and so the game is unresponsive)

**Comment by jnicholl** [comment]
## I have not seen this at all before. I was curious about a) is SDL getting events from libscreen? b) is screen setting up multiple windows and receiving touch events on another one? c) does swiping down from the top affect this at all? 

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by jnicholl** [comment]
Did you discover anything further? I can't seem to write a test case that causes this - perhaps you could send a sample program that causes the freeze so I could try it out?

## Thanks.

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by giorgosgs** [comment]
I am out of office now. Will return in a few days. 
A) I don't know yet.
B) i have one window. Not multiple windows.
C) haven't tried that yet. But swiping up from the bottom works ok and minimizes the app.

**Comment by giorgosgs** [comment]
So far it does not hang!
Can it be because I added the file: bar-descriptor.xml?

**Comment by jnicholl** [comment]
I don't think that should make a difference... did you try swiping down from the top? I was curious if that might cause it.

**Comment by giorgosgs** [comment]
I tried swiping down from the top. Nothing happens. This does not cause it.

**Comment by jnicholl** [comment]
Hmm, that was my only idea so far. If you were somehow using TouchControlOverlay with no controls configured it would probably not respond to touch after swipedown.

## Does it still happen? Were you able to make any simpler test case fail in the same way that you could send us? I haven't managed to reproduce it in my attempts, I'm afraid.

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by giorgosgs** [comment]
I found a way to make it freeze. I just left the game playing without doing anything more than 5 minutes and the click freeze. Does that makes sense? Swipedown does not freeze it or unfreeze it. The game is moving and music is playing, only clicks are not working.

Another thing I noticed: When the clicks are not responding and you quit the app 'SDL_QUIT' does not work. SDL_PollEvent does not send a  'SDL_QUIT' event. Maybe it does not send any events at all and that is why clicks are not working.

**Comment by giorgosgs** [comment]
I gave the game to some beta-testers and they all complain that it freezes. Will try to debug again, maybe something happens...

**Comment by jnicholl** [comment]
Can you give us the game in some form? Or even a simple test program so we can reproduce it? I haven't seen this happen at all, so I don't know what else to propose.

**Comment by giorgosgs** [comment]
If I give you the game as a binary will it help?

**Comment by asimonov-im** [comment]
Yes, it would help. You can email the bar file to jnicholl@rim.com or asimonov@rim.com and we will take a look.

**Comment by giorgosgs** [comment]
It seems this was not SDL fault. It was a fault in my own code. Sorry for bothering you.
