### ISSUE TITLE
Landscape video mode shows up letterboxed and portrait on Dev Alpha

### ISSUE THREAD

**Issue by hardhat** [blackberry/SDL#36]
Hi,

I've been using SDL to port some apps for the BB10 Dev Alpha device.  I've been putting into the bar-descriptor.xml file the hints:

```
<initialWindow>
    <systemChrome>none</systemChrome>
    <transparent>false</transparent>
    <aspectRatio>landscape</aspectRatio>
    <autoOrients>false</autoOrients>
</initialWindow>
```

because I am porting a landscape game.  It worked great when launched remotely from the IDE.  But when I launch from the device, it shows up letterboxed and locked to the portrait screen mode.

I looked through SDL_playbookvideo.c to see if I could figure out a patch, but no luck so far.  Why would it behave differently when launched from the IDE instead of launched from the device?  How can I make it behave the same in both settings?

**Comment by jnicholl** [comment]
I'm afraid launching from the IDE does behave differently and set up different environment variables from launching on device. This sometimes trips me up as well. Can you confirm that you have no environment variables being set on Run that do not exist in your bar-descriptor.xml file?
Also, this somewhat resembles https://github.com/blackberry/SDL/issues/28, but that seemed to have been fixed. I'm assuming you have latest version, and the resolution being requested for the window is fairly reasonable?

**Comment by hardhat** [comment]
Hi,

I'll definitely dump the environment variables so that I can compare.  It is something I was thinking about yesterday, but I hadn't done yet.

I have done the update to the lastest version, but I will double check that there are no old versions of the library in the link path.  I've been using the dynamically compiled and linked version of the library so I should be all up to date.

I did look through a few old bugs to see if I could get any hints but I was unable find a connection.

**Comment by hardhat** [comment]
Okay, well I did the environ list for both circumstances, and they are both identical (these are captured in main before the SDL_init call, if that is the right time to do it):

_=/base/bin/on
PATH=/base/bin:/base/usr/bin:/base/sbin:/base/usr/sbin:/base/usr/photon/bin:/base/scripts:/radio/bin:/radio/usr/bin:/radio/sbin:/radio/usr/sbin:/radio/scripts:/proc/boot:/base/bin:/base/sbin:/base/usr/bin:/base/usr/sbin:/base/opt/bin:/base/usr/sbin
RTC_CLOCK_TYPE=
CELLULAR_NET_IF_PREFIX=cellular
FLASH_FONT_CFG_PATH=/etc/system/config/flash-font.cfg
HMI_REMOTE=FALSE
PLATFORM=Colt
QT_QPA_PLATFORM=blackberry
WLANSUPPVER=06
GRAPHICS_ROOT=/usr/lib/graphics/omap4430
TERM=ansi
MM_INIT=/base/lib/dll/mmedia
CPU=armle-v7
QT_LIB_PATH=/base/usr/lib/qt4/lib
QT_PLUGIN_PATH=/base/usr/lib/qt4/plugins
QML_IMPORT_PATH=/base/usr/lib/qt4/imports
WIFIDEVICE=ti0
PERSISTENCE_DATA=/
RADIO_NET_IF_LIST= cellular0 cellular1 cellular2 cellular3 cellular4
LOGDIR=/var/log
APPCPU=
LD_LIBRARY_PATH=app/native/lib:/usr/lib/appserv
LIBIMG_CFGFILE=/etc/system/config/img.conf
BASEFS=/base
RADIO_BOARD_CONFIG=m5730
RADIOBOARDFILE=/radio/radio.tdf
BOARD_CONFIG=sdk
uname_m=OMAP4460_ES1.1_HS_Colt_Rev:06
QT_QPA_FONTDIR=/base/usr/lib/qt4/fonts
BOARDFILE=/base/board.tdf
WLANDEV=colt
DECKARD_DEBUG=0
BOOT_LOADER=RIMBOOT
PLATFORM_LOWERCASE=colt
LOCFILE=/usr/share/locale/locale.file
FONTCONFIG_FILE=/etc/fontconfig/fonts.conf
STDIO_DEFAULT_BUFSIZE=8192
SYSNAME=nto
ROOTFS=/
PHFONT=/dev/phfont
TMP=//accounts/1000/appdata/com.distantgames.drowned.testDev_mes_drowneda78fde16/tmp
PHKSCOPE=1
WLANCHP=ti1283
HMI_VOLUME_SCALE=50
RTC_OPTS=
PLATFORM_REV=06
LANG=C
PHOTON=/dev/photon
WLANDRV=mcp25
PLATFORM_CLASS=phone
FLASHTMP=/tmp
MIN_VALID_DATE_SEC=1241136000
HOME=//accounts/1000/appdata/com.distantgames.drowned.testDev_mes_drowneda78fde16/data
DECKARD_DEBUG_SCRIPT=0
RADIOFS=/radio
RTC_CLOCK_OPTS=
DISK_ALIMIT=65536
BOOT_START_TIME=1348464710
MIN_VALID_DATE=200905010000.00
PPSDIR=/pps
BMETRICS_NAME=launcher
ORIENTATION=270
ROTATION=left_up
WIDTH=1280
HEIGHT=768
COVERWIDTH=334
COVERHEIGHT=396
TEMP=//accounts/1000/appdata/com.distantgames.drowned.testDev_mes_drowneda78fde16/tmp
NET_PPS_ROOT=/pps/services/networking
PERIMETER=personal
PERIMETER_HOME=/accounts/1000

and yet I still have the differing launch behaviour.  And I am sure I am using the very latest build of libSDL from the latest source code.

**Comment by hardhat** [comment]
So as for your last question, the resolution I'm requesting is low res compared to the device 1280x768. Spectifically 800x600 (popular PC res) for one game or 480x272 (PSP res) for the other two games.  Neither are specifically supported in your special cases but they seem to work well enough in most circumstances I've tried, other than the letter boxing when launched from the device instead of the IDE.

**Comment by jnicholl** [comment]
Hmm, I'm sorry I don't have a quick solution right off. Have you tried playing with the ORIENTATION env var? Also, does defining STRETCHED help with the letterboxing? There should be a reference to that in SDL_playbookvideo, I believe.
Also, are you using opengl?

**Comment by hardhat** [comment]
I will do additional experiments with the ORIENTATION env var.  So I didn't see any effects when I was trying it on the weekend, but I also didn't understand that 270 was the usual value for a portrait resolution.  I suspect that STRETCHED is not going to do the trick for me, since it'll be distorting the game heavily.  At least one of the games I can change to run in portrait mode without too much trouble.  So I guess I'll do that in the short term, until I can find (maybe with your help) how to get consistent landscape.

**Comment by jnicholl** [comment]
We just pushed a change to both TouchControlOverlay and SDL that should fix these issues. Can you try it out?
Thanks!

**Comment by hardhat** [comment]
Awesome change.  It did the trick on the Dev Alpha.  I will consider this totally fixed.
