### ISSUE TITLE
touchcontroloverlay.h seems to be missing

### ISSUE THREAD

**Issue by idispatch** [blackberry/SDL#4]
Searched in NDK and in SDL project - the file can't be found

**Comment by jnicholl** [comment]
Located in https://github.com/blackberry/TouchControlOverlay. 
It's used to map touch controls to keyboard and mouse controls in a configurable way, and it didn't seem like the sort of thing that should be directly included in SDL.

-----Original Message-----
From: Oleg [mailto:reply@reply.github.com] 
Sent: Monday, December 12, 2011 3:27 AM
To: Jeremy Nicholl
Subject: [SDL] touchcontroloverlay.h seems to be missing (#4)

Searched in NDK and in SDL project - the file can't be found

---

Reply to this email directly or view it on GitHub:
https://github.com/blackberry/SDL/issues/4

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by idispatch** [comment]
Could we mention it somewhere in the platform specific Readme.QNX in SDL tree? It is not quiet obvious about whereabouts of this include (and the project wont build right away, the Google would say nothing on touchoverlay.h search). I ended up defining my own header file with stubbing the undefined symbols...

Thanks!

**Comment by jnicholl** [comment]
I'll add the info to the README.md file. This repository doesn't contain the Readme.QNX file.
