### ISSUE TITLE
SDL_mixer issue with SDL

### ISSUE THREAD

**Issue by giorgosgs** [blackberry/SDL#46]
Hi, 

I have an SDL OpenGL game for BB playbook that works fine.
Today I have tested it in my new Blackberry 10 Dev Alpha C device.
Everything works fine except one thing: The music and sound is playing wrong. It sounds like the speaker has a problem. Both the music OGG files and sound effects WAV. I suspect the problem is with SDL_mixer? Can somebody try this? This has to be updated with the launch of the new Q10 device.

Thanks,
Giorgos

**Comment by jnicholl** [comment]
What do the sound problems sound like? Can you describe the issue?
Thanks,
Jeremy

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by giorgosgs** [comment]
The ogg files music sounds like it plays 'discontinuous' and slower. You hear the music on a off many times per sec. The sound effects wav sounds distorted, like it plays slowly and parts of the sound, not all of it. 

I have compiled the SDL_mixer from here: https://github.com/asimonov-im/SDL_mixer at Aug/2012.
But I see that no changes have benn made since then. This is for playbook which by the way runs perfectly.
what about this:? https://github.com/idispatch/SDL_mixer/

Can it be an issue only at the Blackberry Dev Alpha C device because I had no complains so far and the game is up many months now.

I have recorded the distorted music into a OGG file and attach it here: http://rapidshare.com/files/1000379831/music.ogg

**Comment by jnicholl** [comment]
I don’t think it’s likely to be a problem with SDL_mixer directly, but rather how SDL plays sound. Can you try changing the following parameters in SDL and rebuilding?
In src/audio/nto/SDL_nto_audio.c, change DEFAULT_CPARAMS_FRAG_SIZE from 4096 to 2048, and change DEFAULT_CPARAMS_FRAGS_MAX from 1 to 4. I’ve been told this makes the audio playback smoother as there are more fragment buffers available for data.
Thanks!

**Comment by giorgosgs** [comment]
I have tested these changes on the Dev Alpha C and now the sound works fine! Bravo. Both OGG and WAV work ok. I have tested it on the playbook too and it still works fine. Problem solved! You guys are fast.

**Comment by jnicholl** [comment]
Thanks for testing it out, I’ll push the change later today.
Glad it works!
