### ISSUE TITLE
uintptr_t conflict with QNX internal includes.

### ISSUE THREAD

**Issue by trevornunes** [blackberry/SDL#8]
In SDL_config_minimal.h we have ...

typedef unsigned long uintptr_t;

but it's also defined in  stdint.h in the target/qnx6/usr/include directory.

For FCEUXpb I got around this by commenting out the stdint.h typedef but something more flexible is probably required or maybe in SDL_config_minimal.h :
# ifndef **QNXNTO**

typedef ...
# endif

I couldn't get a clean solution working ...

**Comment by jnicholl** [comment]
Thanks for the heads up. Why are you using the minimal configuration, however? Wouldn't it be more natural to use the playbook version? Have you defined **PLAYBOOK**?

-----Original Message-----
From: Trevor Nunes [mailto:reply@reply.github.com] 
Sent: Tuesday, January 03, 2012 4:35 PM
To: Jeremy Nicholl
Subject: [SDL] uintptr_t conflict with QNX internal includes. (#8)

In SDL_config_minimal.h we have ...

typedef unsigned long uintptr_t;

but it's also defined in  stdint.h in the target/qnx6/usr/include directory.

For FCEUXpb I got around this by commenting out the stdint.h typedef but something more flexible is probably required or maybe in SDL_config_minimal.h :

#ifndef **QNXNTO**
typedef ...
#endif

I couldn't get a clean solution working ...

---

Reply to this email directly or view it on GitHub:
https://github.com/blackberry/SDL/issues/8

---

This transmission (including any attachments) may contain confidential information, privileged material (including material protected by the solicitor-client or other applicable privileges), or constitute non-public information. Any use of this information by anyone other than the intended recipient is prohibited. If you have received this transmission in error, please immediately reply to the sender and delete this information from your system. Use, dissemination, distribution, or reproduction of this transmission by unintended recipients is not authorized and may be unlawful.

**Comment by trevornunes** [comment]
i will check my build, i think its set in the sdl lib build its not set in fceux compile however ...

**Comment by jnicholl** [comment]
Can you set it in the fceux compile just to see?

-----Original Message-----

**Comment by a7omic** [comment]
I saw this too when I compiled your FCEUX project, I just commented it out in SDL_config_minimal.h.
